services:
  - type: web
    name: vectordeck
    env: node
    plan: free
    buildCommand: npm install && npm run build:data
    startCommand: npm start
    envVars:
      - key: HOST
        value: 0.0.0.0
      - key: NODE_ENV
        value: production
